version: '3.8'

services:
  # 1. MongoDB Persistent Database Service
  database:
    image: mongo:latest
    container_name: careervault-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # 2. Node Express Backend Service
  backend:
    build: ./backend
    container_name: careervault-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://database:27017/careervault
      - JWT_SECRET=careervault_super_secret_jwt_key_12345_abc
      - NODE_ENV=development
    depends_on:
      - database

  # 3. React Vite Frontend Client Service
  frontend:
    build: ./frontend
    container_name: careervault-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

# Declare Docker Volume to prevent data wipeout on container restarts
volumes:
  mongo-data:
